
//DECLARE ALL PERMITED ACTIONS
export const GET_CONFIG_REQUEST = 'GET_CONFIG_REQUEST';
export const GET_CONFIG_SUCCESS = 'GET_CONFIG_SUCCESS';
export const GET_CONFIG_ERROR = 'GET_CONFIG_ERROR';
export const RESET_CONFIG = 'RESET_CONFIG';
export const UPDATE_AMOUNT = 'UPDATE_AMOUNT';
export const UPDATE_PERIOD = 'UPDATE_PERIOD';
export const UPDATE_RCF_INTEREST = 'UPDATE_RCF_INTEREST';
export const UPDATE_LOAN_INTEREST = 'UPDATE_LOAN_INTEREST';
export const STORE_RESULT = 'STORE_RESULT';